apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: hello-world
  name: hello-world-monitor
spec:
  endpoints:
    - interval: 5s
      port: metrics
  selector:
    matchLabels:
      app: hello-world-istio