kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-latency-rules
  labels:
    role: prometheus-rulefiles
    prometheus: prometheus-helloworld 
data:
  latency.rules: |
    # Alert for any instance that is unreachable for >5 minutes.
    ALERT InstanceDown
      IF up == 0
      FOR 5m
      LABELS { severity = "page" }
      ANNOTATIONS {
        summary = "Instance {{ $labels.instance }} down",
        description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.",
      }

    # Alert for any instance that have a median request latency >1s.
    ALERT APIHighRequestLatency
      IF rate(flask_request_latency_seconds_sum[1m]) / rate(flask_request_latency_seconds_count[1m]) > 1 
      FOR 1m
      ANNOTATIONS {
        summary = "High request latency on {{ $labels.instance }}",
        description = "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)",
      }
